version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ./env/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
