services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ./env/.env.docker
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: faqdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
